config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  root to: "pages#home"
  resources :playlists, only: [:index, :show, :new, :create, :destroy]
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }, skip: [:session]
  as :user do
    delete "/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  validates :user, presence: true
  validates :name, presence: true
  validate :at_least_one_critera_is_filled
  validates :energy, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 100, only_integer: true, allow_nil: true }
  validates :danceability, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 100, only_integer: true, allow_nil: true }
  validates :genre, inclusion: { in: PlaylistsHelper::GENRES, message: "Please select a valid genre", allow_nil: true }

  def at_least_one_critera_is_filled
    if energy.blank? && danceability.blank? && genre.blank?
      errors.add :base, :invalid, message: "You must define at least one of those criteria to generate your playlist: genre, energy or danceability"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :playlists, dependent: :destroy
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: %i[spotify]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    playlists_path
  end
end

app/controllers/authenticated_user_controller.rb
class AuthenticatedUserController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def spotify
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      affect_spotify_tokens!(request.env["omniauth.auth"].credentials)
      sign_in_and_redirect @user # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Spotify") if is_navigational_format?
    else
      session["devise.spotify_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    flash[:error] = "La connexion a échoué. Merci de réessayer ultérieurement."
    redirect_to root_path
  end

  private

  def affect_spotify_tokens!(credentials)
    @user.refresh_token = credentials.refresh_token
    @user.token = credentials.token
    @user.save!
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/controllers/playlists_controller.rb
require 'rspotify'

class PlaylistsController < AuthenticatedUserController

  def index
    @playlists = Playlist.all
  end

  def show
    @playlist = Playlist.find(params[:id])
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.new(playlist_params)

    if @playlist.valid?
      @playlist.spotify_id = PlaylistCreator.new(@playlist).generate_from_seeds
    end

    if @playlist.save
      redirect_to playlist_path(@playlist)
    else
      render :new
    end
  end

  def destroy
    @playlist = Playlist.find(params[:id])
    if @playlist.destroy
      PlaylistDestructor.new(@playlist).perform
    end
    redirect_to playlists_path
  end

  private

  def playlist_params
    params.require(:playlist).permit(:name, :genre, :danceability, :energy, :spotify_id).merge(user: current_user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
  GENRES = ["acoustic",
            "afrobeat",
            "alt-rock",
            "alternative",
            "ambient",
            "anime",
            "black-metal",
            "bluegrass",
            "blues",
            "bossanova",
            "brazil",
            "breakbeat",
            "british",
            "cantopop",
            "chicago-house",
            "children",
            "chill",
            "classical",
            "club",
            "comedy",
            "country",
            "dance",
            "dancehall",
            "death-metal",
            "deep-house",
            "detroit-techno",
            "disco",
            "disney",
            "drum-and-bass",
            "dub",
            "dubstep",
            "edm",
            "electro",
            "electronic",
            "emo",
            "folk",
            "forro",
            "french",
            "funk",
            "garage",
            "german",
            "gospel",
            "goth",
            "grindcore",
            "groove",
            "grunge",
            "guitar",
            "happy",
            "hard-rock",
            "hardcore",
            "hardstyle",
            "heavy-metal",
            "hip-hop",
            "holidays",
            "honky-tonk",
            "house",
            "idm",
            "indian",
            "indie",
            "indie-pop",
            "industrial",
            "iranian",
            "j-dance",
            "j-idol",
            "j-pop",
            "j-rock",
            "jazz",
            "k-pop",
            "kids",
            "latin",
            "latino",
            "malay",
            "mandopop",
            "metal",
            "metal-misc",
            "metalcore",
            "minimal-techno",
            "movies",
            "mpb",
            "new-age",
            "new-release",
            "opera",
            "pagode",
            "party",
            "philippines-opm",
            "piano",
            "pop",
            "pop-film",
            "post-dubstep",
            "power-pop",
            "progressive-house",
            "psych-rock",
            "punk",
            "punk-rock",
            "r-n-b",
            "rainy-day",
            "reggae",
            "reggaeton",
            "road-trip",
            "rock",
            "rock-n-roll",
            "rockabilly",
            "romance",
            "sad",
            "salsa",
            "samba",
            "sertanejo",
            "show-tunes",
            "singer-songwriter",
            "ska",
            "sleep",
            "songwriter",
            "soul",
            "soundtracks",
            "spanish",
            "study",
            "summer",
            "swedish",
            "synth-pop",
            "tango",
            "techno",
            "trance",
            "trip-hop",
            "turkish",
            "work-out",
            "world-music"
          ]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpotifyGenerator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/_banner.html.erb
<div class="banner"">
  <div class="container">
    <h1>Créez vos playlists personnalisées</h1>
    <h5>Créez et enregistrez vos playlists personnalisées en quelques clics ! Ces playlists seront directement ajoutées à votre compte Spotify.</h5>
    <%= link_to "Me connecter avec Spotify", user_spotify_omniauth_authorize_path, class: "btn-signin" %>
    <p class="ml">Veuillez utiliser le compte Spotify test ou demander à l'administrateur d'ajouter votre compte Spotify en tant que compte test pour pouvoir vous connecter.</p>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'banner' %>

app/views/playlists/index.html.erb
<div class="background">
  <div class="container">
    <div class="playlists-wrapper">
      <div class="playlists-headers">
        <div>
          <h1>Toutes les playlists</h1>
        </div>
        <div class="link-playlists">
          <%= link_to "Créer une playlist", new_playlist_path %>
        </div>
      </div>
      <div class="pt-3 playlist-cards">
        <% @playlists.each do |playlist| %>
          <% if playlist.user_id == current_user.id %>
            <div class="playlist-card">
              <%= link_to playlist_path(playlist) do %>
              <div class="playlist-img"
                  <% if playlist.danceability.nil? %>
                    style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path("energie0.jpg")%>')";
                  <% elsif playlist.danceability < 25 %>
                    style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path("energie1.jpg")%>')";
                  <% elsif playlist.danceability < 50 %>
                    style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path("energie2.jpg")%>')";
                  <% elsif playlist.danceability < 74 %>
                    style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path("energie3.jpg")%>')";
                  <% else %>
                    style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path("energie4.jpg")%>')";
                <% end %>>
                <h3><%= playlist.name %></h3>
              </div>
              <% end %>
              <div class="playlist-info">
                <div class="playlist-name">
                  <%= playlist.name %>
                </div>
                <div class="playlist-genre">
                  <%= playlist.genre %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/playlists/new.html.erb
<div class="form-wrapper">
  <div class="container">
    <div class="playlists-headers">
        <div>
          <h1>Créer une playlist</h1>
        </div>
        <div class="link-playlists">
          <%= link_to "Toutes les playlists", playlists_path %>
        </div>
      </div>
    <div class="row justify-content-center form-body">
        <%= simple_form_for(@playlist) do |f| %>
          <%= f.error_notification %>
          <% if f.object.errors[:base].present? %>
            <%= f.error_notification message: f.object.errors[:base].to_sentence %>
          <% end %>
          <%= f.input :name, label: "Nom de la playlist" %>
          <%= f.input :genre, as: :select, collection: PlaylistsHelper::GENRES, prompt: 'Sélectionner le genre', label: "Genre musical" %>
          <%= f.input :danceability, collection: (1..100).to_a, prompt: "De 1 (pas du tout) à 100 (je veux danser jusqu'à épuisement)", label: "Niveau de rythme" %>
          <%= f.input :energy, collection: (1..100).to_a, prompt: "De 1 (dimanche soir dans mon canapé) à 100 (pile Duracell)", label: "Niveau d'énergie" %>
          <%= f.submit "Ajouter", class: "mt-2 btn btn-dark" %>
        <% end %>
    </div>
  </div>
</div>

app/views/playlists/show.html.erb
<div class="background">
  <div class="container">
   <div class="playlist-wrapper">
      <div class="playlists-headers">
        <div>
          <h1><%= @playlist.name.capitalize %></h1>
        </div>
        <div class="link-playlists">
          <%= link_to "Toutes les playlists", playlists_path %>
        </div>
      </div>
      <div class="infos">
        <div class="infos-left">
          <div class="img"
            <% if @playlist.danceability.nil? %>
              style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path("energie0.jpg")%>')";
            <% elsif @playlist.danceability < 25 %>
              style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path("energie1.jpg")%>')";
            <% elsif @playlist.danceability < 50 %>
              style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path("energie2.jpg")%>')";
            <% elsif @playlist.danceability < 74 %>
              style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path("energie3.jpg")%>')";
            <% else %>
              style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path("energie4.jpg")%>')";
            <% end %>>
          </div>
          <div class="info-text">
          <ul class="details">
            <% if @playlist.genre.present? %>
              <li>Genre : <%= @playlist.genre.capitalize %></li>
            <% end %>
            <% if @playlist.energy.present? %>
              <li>Energie :
                <% if @playlist.energy < 25 %>
                  +
                <% elsif @playlist.energy < 50 %>
                  ++
                <% elsif @playlist.energy < 74 %>
                  +++
                <% else %>
                  ++++
                <% end %>
              </li>
            <% end %>
            <% if @playlist.danceability.present? %>
              <li>Rythme :
                <% if @playlist.danceability < 25 %>
                  +
                <% elsif @playlist.danceability < 50 %>
                  ++
                <% elsif @playlist.danceability < 74 %>
                  +++
                <% else %>
                  ++++
                <% end %>
              </li>
            <% end %>
          </ul>
          <div class="delete-playlists">
            <%= link_to "Supprimer", playlist_path(@playlist), method: :delete, data:{confirm: "Etes vous sûr de vouloir supprimer cette playlist?"}, class: "delete-link"%>
          </div>
        </div>
        </div>
        <div class="listen-link">
          <%= link_to "https://open.spotify.com/playlist/#{@playlist.spotify_id}", target: :_blank do %>
            <div class="play">
              <i class="fas fa-play"></i>
            </div>
            <div>
              <p>Ecouter</p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible m-3" role="alert">
    <button type="button" class="close btn btn-light p-1" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible m-3" role="alert">
    <button type="button" class="close btn btn-light p-1" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="logo">
    <%= link_to root_path do %>
      <h2>Playlistator</h2>
    <% end %>
  </div>
  <div class="login">
      <% if user_signed_in? %>
          <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "login-out" %>
      <% else %>
          <%= link_to "Connexion",  user_spotify_omniauth_authorize_path, class: "login-out" %>
      <% end %>
  </div>
</div>